image:
  file: .gitpod.Dockerfile

tasks:
  - name: Gitpod Init
    init: |
      export DDEV_NONINTERACTIVE=true
      .ddev/gitpod-setup-ddev.sh
      ddev composer install
    command: |
      .ddev/gitpod-setup-ddev.sh
vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - skippednote.vs-code-drupal
