<?php

/**
 * @file
 * Functions to support theming in the drupalastic theme.
 */

/**
* Implements drupalastic_suggestions_page_alter().
*/
function drupalastic_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'page__' . $node->bundle();
  }
}

function drupalastic_preprocess(&$variables, $hook) {
  $variables['base_path'] = base_path();
}
